name: app_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  http: ^1.6.0
  json_annotation: ^4.9.0
  provider: ^6.1.5+1
  dio: ^5.9.0
  retrofit: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  retrofit_generator: ^10.2.0

dependency_overrides:
  analyzer: ^8.0.0

flutter:
  uses-material-design: true
